$(document).ready(function(){
	$('.tabs').tabs();
	$('.modal').modal();
	$('.collapsible').collapsible();
	$('.sidenav').sidenav();
	$('input.pkmn-autocomplete').autocomplete({ 
		data: {
			"Bulbasaur": null,
			"Charmander": null,
			"Squirtle": null,
			"Caterpie": null,
			"Weedle": null,
			"Pidgey": null,
			"Rattata": null,
			"Spearow": null,
			"Ekans": null,
			"Pikachu": null,
			"Sandshrew": null,
			"Nidoran♀": null,
			"Nidoran♂": null,
			"Clefairy": null,
			"Vulpix": null,
			"Jigglypuff": null,
			"Zubat": null,
			"Oddish": null,
			"Paras": null,
			"Venonat": null,
			"Diglett": null,
			"Meowth": null,
			"Psyduck": null,
			"Mankey": null,
			"Growlithe": null,
			"Poliwag": null,
			"Abra": null,
			"Machop": null,
			"Bellsprout": null,
			"Tentacool": null,
			"Geodude": null,
			"Ponyta": null,
			"Slowpoke": null,
			"Magnemite": null,
			"Farfetch'd": null,
			"Doduo": null,
			"Seel": null,
			"Grimer": null,
			"Shellder": null,
			"Gastly": null,
			"Onix": null,
			"Drowzee": null,
			"Krabby": null,
			"Voltorb": null,
			"Exeggcute": null,
			"Cubone": null,
			"Hitmonlee": null,
			"Hitmonchan": null,
			"Lickitung": null,
			"Koffing": null,
			"Rhyhorn": null,
			"Chansey": null,
			"Tangela": null,
			"Kangaskhan": null,
			"Horsea": null,
			"Goldeen": null,
			"Staryu": null,
			"Mr. Mime": null,
			"Scyther": null,
			"Jynx": null,
			"Electabuzz": null,
			"Magmar": null,
			"Pinsir": null,
			"Tauros": null,
			"Magikarp": null,
			"Lapras": null,
			"Ditto": null,
			"Eevee": null,
			"Porygon": null,
			"Omanyte": null,
			"Kabuto": null,
			"Aerodactyl": null,
			"Snorlax": null,
			"Articuno": null,
			"Zapdos": null,
			"Moltres": null,
			"Dratini": null,
			"Mewtwo": null,
			"Mew": null
		},
		onAutocomplete: function(pkmnName){
			startPkmnSearch(pkmnName);
		}
	})
});